[wokwi]
version = 1
firmware = './.pio/build/esp32/firmware.bin'
elf = './.pio/build/esp32/firmware.elf'
rfc2217ServerPort = 4001
upload_port = "COM1"

# Forward http://localhost:8180 to port 80 on the simulated ESP32:
[[net.forward]]
from = "localhost:8180"
to = "target:80"

[[chip]]
name = 'mq2'
binary = 'chips/mq2.chip.wasm'

[[serial]]
name = "com1"
baud = 115200

[[serial]]
name = "com2" 
baud = 9600